language: go

services:
  - postgresql

go:
- master

env:
  - GO111MODULE=on

notifications:
  email: false

before_script:
  - createuser -s coffeeworks
  - psql -c 'create database coffeeworks_test;' -U coffeeworks -d postgres

script:
  - go test -v -race ./...
