development:
  dialect: postgres
  database: coffeeworks_development
  user: coffeeworks
  password: coffeeworks
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://coffeeworks:coffeeworks@127.0.0.1:5432/coffeeworks_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://coffeeworks:coffeeworks@127.0.0.1:5432/coffeeworks?sslmode=disable"}}
